openapi: 3.0.0
info:
  title: Smart AI Event Assistant API
  version: 1.1.0
  description: อัปเดต API ให้ response organizer_id ใน user ทุก endpoint ที่เกี่ยวข้อง

servers:
  - url: http://localhost:8080

paths:
  /users/register:
    post:
      summary: สมัครสมาชิก
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: Register successful
        '400':
          description: Invalid request

  /users:
    get:
      summary: ดึงข้อมูลผู้ใช้ทั้งหมด
      responses:
        '200':
          description: OK

    post:
      summary: สร้างผู้ใช้ใหม่
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: Created

  /users/{id}:
    get:
      summary: ดึงข้อมูลผู้ใช้ตาม ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithOrganizerID'

    put:
      summary: อัปเดตข้อมูลผู้ใช้
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Updated

    delete:
      summary: ลบผู้ใช้
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Deleted

  /login:
    post:
      summary: ล็อกอิน
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/UserWithOrganizerID'
        '401':
          description: Email or password incorrect

  /organizers:
    get:
      summary: ดึงข้อมูล Organizer ทั้งหมด
      responses:
        '200':
          description: OK
    post:
      summary: สร้าง Organizer ใหม่
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organizer'
      responses:
        '201':
          description: Created

  /organizers/{id}:
    get:
      summary: ดึง Organizer ตาม ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
    put:
      summary: อัปเดต Organizer
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organizer'
      responses:
        '200':
          description: Updated
    delete:
      summary: ลบ Organizer
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Deleted

  /organizer_portfolios/organizer/{organizer_id}:
    get:
      summary: ดึงผลงานทั้งหมดของ Organizer ตาม organizer_id
      parameters:
        - in: path
          name: organizer_id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Portfolio'

  /events:
    get:
      summary: ดึงข้อมูล Event ทั้งหมด
      responses:
        '200':
          description: OK
    post:
      summary: สร้าง Event ใหม่
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Created

  /events/{id}:
    get:
      summary: ดึง Event ตาม ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
    put:
      summary: อัปเดต Event
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Updated
    delete:
      summary: ลบ Event
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Deleted

components:
  schemas:
    UserRegister:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required: [username, email, password]

    UserUpdate:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        bio:
          type: string
        profile_image:
          type: string

    UserWithOrganizerID:
      type: object
      properties:
        user_id:
          type: integer
        username:
          type: string
        email:
          type: string
        role:
          type: string
        organizer_id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        bio:
          type: string
        profile_image:
          type: string
        created_at:
          type: string
          format: date-time

    Organizer:
      type: object
      properties:
        organizer_id:
          type: integer
        user_id:
          type: integer
        portfolio_img:
          type: string
        expertise:
          type: string
        created_at:
          type: string
          format: date-time

    Portfolio:
      type: object
      properties:
        portfolio_id:
          type: integer
        organizer_id:
          type: integer
        title:
          type: string
        description:
          type: string
        image_url:
          type: string
        category:
          type: string
        price:
          type: string
        created_at:
          type: string
          format: date-time

    Event:
      type: object
      properties:
        event_id:
          type: integer
        name:
          type: string
        description:
          type: string
        organizer_id:
          type: integer
        event_image:
          type: string
        created_at:
          type: string
          format: date-time